const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];let state={connections:[],keys:[]},selectedKey=null,logTimer=null;
const BASE=location.pathname.replace(/[^/]*$/,'').replace(/\/$/,'');
const api=async(url,o={})=>{const r=await fetch(BASE+url,{...o,headers:{'Content-Type':'application/json',...(state.csrf?{'X-CSRF-Token':state.csrf}:{}),...(o.headers||{})}});let d={};try{d=await r.json()}catch{}if(r.status===401){showLogin();throw Error('unauthorized')}if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d};
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(s,e=false){const t=$('#toast');t.textContent=s;t.className='toast'+(e?' error':'');setTimeout(()=>t.classList.add('hidden'),4200)}
function showLogin(){$('#app').classList.add('hidden');$('#loginView').classList.remove('hidden')}function showApp(){$('#loginView').classList.add('hidden');$('#app').classList.remove('hidden')}
function help(k){return `<button type="button" class="help" data-help="${k}">?</button>`}function label(t,k){return `<div class="label-row"><label>${t}</label>${help(k)}</div>`}
function connectionForm(){const p=state.suggested_port||50001;return `<form id="connectionForm"><div class="form-grid"><div class="field">${label('Название','name')}<input name="name" value="Main" required></div><div class="field">${label('Порт','port')}<input name="port" type="number" min="1" max="65535" value="${p}" required></div><div class="field">${label('Метод шифрования','aead')}<select name="aead"><option value="chacha20-poly1305">ChaCha20-Poly1305</option><option value="aes-128-gcm">AES-128-GCM</option><option value="none">None — без AEAD</option></select></div><div class="field">${label('Тип таблицы','table')}<select name="table"><option value="up_ascii_down_entropy">Отправка ASCII / загрузка Low Entropy</option><option value="prefer_entropy">Низкая энтропия</option><option value="prefer_ascii">ASCII</option><option value="up_entropy_down_ascii">Отправка Low Entropy / загрузка ASCII</option></select></div><div class="field full">${label('Padding','padding')}<div class="toggle-row"><input name="pmin" type="number" min="0" max="100" value="2" aria-label="Минимум"><input name="pmax" type="number" min="0" max="100" value="7" aria-label="Максимум"></div></div><div class="field full"><div class="toggle-row"><label class="toggle"><input name="pure" type="checkbox">Pure Downlink ${help('pure')}</label><label class="toggle"><input name="http" type="checkbox">HTTP-маскировка ${help('http')}</label></div></div><details class="field full advanced"><summary>Дополнительные параметры</summary><div class="form-grid"><div class="field">${label('Multiplex','multiplex')}<select name="multiplex"><option value="off">Выключено</option><option value="auto">Auto</option><option value="on">Включено</option></select></div><div class="field http-mode hidden">${label('Режим HTTP','httpMode')}<select name="httpMode"><option value="auto">Auto</option><option value="stream">Stream</option><option value="poll">Poll</option><option value="ws">WebSocket</option><option value="legacy">Legacy</option></select></div></div></details></div><div class="submit-row"><button class="primary" type="submit">Создать Sudoku</button></div></form>`}
async function boot(){try{state=await api('/api/state');showApp();render();metrics()}catch(e){if(e.message!=='unauthorized')toast(e.message,true)}}
function render(){const c=state.connections[0];$('#setupView').classList.toggle('hidden',!!c);$('#homeView').classList.toggle('hidden',!c);if(!c){$('#setupForm').innerHTML=connectionForm();bindConnectionForm();$('#serviceStatus').className='status off';$('#serviceStatus').textContent='● Не настроен';return}$('#serviceStatus').className='status '+(c.active?'':'error');$('#serviceStatus').textContent=c.active?'● Работает':'● Ошибка';$('#connectionName').textContent=c.name;$('#endpoint').textContent=`${location.hostname} : ${c.port}`;if(!selectedKey||!state.keys.some(k=>(k.ID||k.id)===selectedKey))selectedKey=state.keys[0]?.ID||state.keys[0]?.id||null;renderKeys();renderHero(c)}
function bindConnectionForm(){const f=$('#connectionForm');f.http.onchange=()=>$('.http-mode',f).classList.toggle('hidden',!f.http.checked);f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);if(d.get('aead')==='none'&&!confirm('Шифрование Sudoku будет отключено. Продолжить только для тестирования?'))return;const min=+d.get('pmin'),max=+d.get('pmax');if(min<0||max>100||min>max)return toast('Padding: 0 ≤ минимум ≤ максимум ≤ 100',true);f.classList.add('loading');toast('Создаём ключи и запускаем Sudoku…');try{await api('/api/connections',{method:'POST',body:JSON.stringify({name:d.get('name'),port:+d.get('port'),AEAD:d.get('aead'),TableType:d.get('table'),PaddingMin:min,PaddingMax:max,PureDownlink:d.get('pure')==='on',HTTPMask:d.get('http')==='on',HTTPMode:d.get('httpMode'),Multiplex:d.get('multiplex')})});state=await api('/api/state');render();toast('Sudoku работает')}catch(x){toast(x.message,true);f.classList.remove('loading')}}}
function renderKeys(){const list=$('#keysList');if(!state.keys.length){list.innerHTML='<p class="muted">Ключей доступа пока нет.</p>';return}list.innerHTML=state.keys.map(k=>{const id=k.ID||k.id,n=k.Name||k.name;return `<div class="key-row ${id===selectedKey?'selected':''}" data-select-key="${id}"><b>${esc(n)}</b><div class="key-actions"><button class="icon-action" data-qr="${id}" title="Показать QR для импорта" aria-label="Показать QR">▦</button><button class="icon-action" data-copy="${id}" title="Скопировать ссылку импорта" aria-label="Скопировать ссылку">⧉</button><button class="icon-action" data-clash="${id}" title="Скачать конфигурацию ClashMi" aria-label="Скачать конфигурацию ClashMi">⇩</button><button class="icon-action" data-manual="${id}" title="Параметры ключа" aria-label="Параметры ключа">ⓘ</button><button class="icon-action" data-rename="${id}" title="Переименовать" aria-label="Переименовать">✎</button><button class="icon-action danger-icon" data-delete-key="${id}" title="Удалить" aria-label="Удалить">⌫</button></div></div>`}).join('')}
function renderHero(c){
  const k=state.keys.find(x=>(x.ID||x.id)===selectedKey);
  $('#selectedKeyText').textContent=k?'Ключ: '+(k.Name||k.name):'Ключей доступа пока нет';
  $('#heroActions').innerHTML=k?'<button class="primary" data-qr="'+selectedKey+'">Показать QR</button><button data-copy="'+selectedKey+'">Скопировать ссылку</button>':'<button class="primary" data-action="new-key">＋ Создать первый ключ</button>';
  $('#heroQR').innerHTML=k?'<img src="'+BASE+'/api/keys/'+selectedKey+'/qr" alt="QR">':'';
}
function modal(html){$('#modalContent').innerHTML=html;$('#modalBackdrop').classList.remove('hidden')}function closeModal(){clearInterval(logTimer);$('#modalBackdrop').classList.add('hidden')}
async function newKey(){
  modal('<h2>Новый ключ</h2><form id="keyForm"><div class="field">'+label('Название','keyName')+'<input name="name" value="iPhone" required></div><div class="modal-actions"><button type="button" id="cancel">Отмена</button><button class="primary">Создать</button></div></form>');
  $('#cancel').onclick=closeModal;
  $('#keyForm').onsubmit=async e=>{e.preventDefault();const n=new FormData(e.target).get('name'),c=state.connections[0];try{const x=await api('/api/keys',{method:'POST',body:JSON.stringify({Name:n,ConnectionID:c.id})});state=await api('/api/state');selectedKey=x.id;showCreated(selectedKey,n)}catch(x){toast(x.message,true)}};
}
async function showCreated(id,n){const x=await api(`/api/keys/${id}/link`);modal(`<div class="qr-created"><h2>QR для импорта</h2><p><b>${esc(n)}</b></p><img src="${BASE}/api/keys/${id}/qr"><p class="muted">HTTPS-подписка для Shadowrocket и ClashMi.</p><div class="modal-actions"><button data-manual="${id}">Параметры</button><button class="primary" data-copy="${id}">Скопировать ссылку</button></div></div>`)}
async function manual(id){const p=await api(`/api/keys/${id}/params`),k=state.keys.find(x=>(x.ID||x.id)===id);const rows=[['Адрес',p.server],['Порт',p.port],['Ключ',p.key],['Метод',p.aead],['Тип таблицы',p.table_type],['Padding',String(p.padding_min)+'–'+String(p.padding_max)],['Pure Downlink',p.pure_downlink?'Включено':'Выключено'],['HTTP Mask',p.http_mask?'Включено':'Выключено'],['Multiplex',p.multiplex||'Выключено']];modal(`<h2>Параметры — ${esc(k?.Name||k?.name)}</h2>${rows.map(([a,b])=>`<div class="param-row"><b>${a}</b><code>${esc(b)}</code><button data-copy-value="${esc(b)}">Копировать</button></div>`).join('')}<p class="muted">Используйте эти данные для ручной настройки, если импорт ссылки или QR недоступен.</p>`)}
async function copyLink(id){const x=await api(`/api/keys/${id}/link`);await navigator.clipboard.writeText(x.link);toast('Ссылка импорта скопирована')}
async function downloadClash(id){const r=await fetch(BASE+`/api/keys/${id}/clash.yaml`,{headers:{...(state.csrf?{'X-CSRF-Token':state.csrf}:{})}});if(!r.ok)throw Error('Не удалось создать Clash-конфигурацию');const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sudoku-clash.yaml';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Clash YAML скачан')}
function keyMenu(id){const k=state.keys.find(x=>(x.ID||x.id)===id);modal(`<h2>${esc(k?.Name||k?.name||'Ключ')}</h2><div class="menu-list"><button data-qr="${id}">Показать QR</button><button data-copy="${id}">Скопировать ссылку</button><button data-manual="${id}">Показать параметры</button><button data-rename="${id}">Переименовать</button><button class="danger" data-delete-key="${id}">Удалить из панели</button></div>`)}
function renameKey(id){const k=state.keys.find(x=>(x.ID||x.id)===id);modal(`<h2>Переименовать ключ</h2><form id="renameForm"><input name="name" value="${esc(k?.Name||k?.name)}" required><div class="modal-actions"><button class="primary">Сохранить</button></div></form>`);$('#renameForm').onsubmit=async e=>{e.preventDefault();await api(`/api/keys/${id}`,{method:'PATCH',body:JSON.stringify({name:new FormData(e.target).get('name')})});state=await api('/api/state');closeModal();render();toast('Название сохранено')}}
async function deleteKey(id){if(!confirm('Ключ исчезнет из панели, но уже экспортированная копия продолжит работать. Для настоящего отзыва нужно сменить Master Key. Удалить?'))return;await api(`/api/keys/${id}`,{method:'DELETE'});state=await api('/api/state');selectedKey=null;closeModal();render();toast('Ключ удалён из панели')}
function connectionSettings(){const c=state.connections[0];if(!c)return;const rows=[['Название',c.name],['Порт',c.port],['Метод',c.aead],['Тип таблицы',c.table_type],['Padding',c.padding_min+'–'+c.padding_max],['Pure Downlink',c.pure_downlink?'Включено':'Выключено'],['HTTP Mask',c.http_mask?'Включено':'Выключено'],['Multiplex',c.multiplex||'off']];modal(`<h2>Параметры подключения</h2><p class="muted">Это текущая конфигурация сервера Sudoku. Обычно сюда заходить не нужно; она полезна для проверки настроек и диагностики подключения.</p>${rows.map(([a,b])=>`<div class="param-row"><b>${a}</b><code>${esc(b)}</code></div>`).join('')}`)}
async function logs(){modal('<h2>Логи Sudoku</h2><pre id="logBox" class="logs">Загрузка…</pre><div class="modal-actions"><button id="clearLogs">Очистить окно</button><button id="copyLogs">Копировать</button><button class="primary" id="closeLogs">Закрыть</button></div>');const load=async()=>{const x=await api('/api/logs');const b=$('#logBox');if(b)b.textContent=x.logs};await load();logTimer=setInterval(load,3000);$('#clearLogs').onclick=()=>$('#logBox').textContent='';$('#copyLogs').onclick=()=>navigator.clipboard.writeText($('#logBox').textContent);$('#closeLogs').onclick=closeModal}
async function updates(){modal('<h2>Обновления</h2><p class="muted">Проверяем GitHub Releases…</p>');const u=await api('/api/updates');const row=(title,x,kind,err)=>`<div class="param-row"><b>${title}</b><span>Установлено: ${esc(x.installed)}<br>Последнее: ${esc(x.latest||'неизвестно')}${err?'<br>'+esc(err):''}</span><button data-update="${kind}">${x.available?'Обновить':'Проверить'}</button></div>`;modal(`<h2>Обновления</h2>${row('Sudoku Core',u.core,'core',u.core_error)}${row('Sudoku UI',u.panel,'panel',u.panel_error)}`)}
async function update(kind){toast('Скачиваем и проверяем обновление…');try{const x=await api(`/api/update/${kind}`,{method:'POST'});toast(x.message);if(x.updated)setTimeout(()=>location.reload(),1400)}catch(e){toast(e.message,true)}}
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-select-key]');if(!b){$('#popover').classList.add('hidden');return}try{if(b.dataset.help){const p=$('#popover'),r=b.getBoundingClientRect();p.textContent=HELP[b.dataset.help];p.style.left=Math.min(r.left,innerWidth-350)+'px';p.style.top=(r.bottom+8)+'px';p.classList.remove('hidden');return}if(!b.closest('#popover'))$('#popover').classList.add('hidden');if(b.dataset.selectKey){selectedKey=b.dataset.selectKey;render();return}if(b.dataset.rename)return renameKey(b.dataset.rename);if(b.dataset.deleteKey)return deleteKey(b.dataset.deleteKey);if(b.dataset.action==='new-key')return newKey();if(b.dataset.action==='logout'){await api('/api/logout',{method:'POST'});state={connections:[],keys:[]};return showLogin()}if(b.dataset.action==='logs')return logs();if(b.dataset.action==='updates')return updates();if(b.dataset.action==='restart'){await api(`/api/connections/${state.connections[0].id}/restart`,{method:'POST'});return toast('Sudoku перезапущен')}if(b.dataset.action==='settings')return connectionSettings();if(b.dataset.qr)return showCreated(b.dataset.qr,state.keys.find(k=>(k.ID||k.id)===b.dataset.qr)?.Name||'Ключ');if(b.dataset.copy)return copyLink(b.dataset.copy);if(b.dataset.clash)return downloadClash(b.dataset.clash);if(b.dataset.manual)return manual(b.dataset.manual);if(b.dataset.copyValue){await navigator.clipboard.writeText(b.dataset.copyValue);return toast('Скопировано')}if(b.dataset.update)return update(b.dataset.update)}catch(x){toast(x.message,true)}});
$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal()};$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/login',{method:'POST',body:JSON.stringify({Username:$('#loginUser').value,Password:$('#loginPass').value})});boot()}catch(x){$('#loginError').textContent=x.message}};
async function metrics(){try{const m=await api('/api/metrics');$('#metrics').textContent=`CPU ${m.cpu_percent.toFixed(0)}% · RAM ${Math.round(m.memory_used/1048576)} MB · Диск ${m.disk_percent.toFixed(0)}% · ↓ ${rate(m.rx_rate)} · ↑ ${rate(m.tx_rate)}`}catch{}setTimeout(metrics,2500)}function rate(n){for(const u of ['B/s','KB/s','MB/s','GB/s']){if(n<1024)return `${n.toFixed(n<10?1:0)} ${u}`;n/=1024}return `${n.toFixed(1)} TB/s`}
boot();
