(()=>{
'use strict';
const TEXT={ru:{play:'Поиграем',title:'Классический Sudoku',subtitle:'Небольшая пауза прямо в панели',difficulty:'Сложность',easy:'Легко',medium:'Средне',hard:'Сложно',expert:'Эксперт',newGame:'Новая игра',time:'Время',mistakes:'Ошибки',hints:'Подсказки',notes:'Заметки',erase:'Стереть',hint:'Подсказка',check:'Проверить',pause:'Пауза',resume:'Продолжить',settings:'Настройки',highlight:'Подсвечивать связанные клетки',showMistakes:'Показывать ошибки',showTimer:'Показывать таймер',autoNotes:'Убирать использованные заметки',paused:'Игра на паузе',ready:'Выберите клетку и поставьте цифру.',correct:'Пока всё верно.',incomplete:'Есть пустые клетки.',hasErrors:'Есть ошибки: ',complete:'Готово! Судоку решён.',failed:'Лимит ошибок исчерпан. Начните новую игру.',noHints:'Подсказки для этой партии закончились.',confirmNew:'Начать новую игру? Текущая партия будет заменена.',close:'Закрыть игру',cell:'Клетка'},en:{play:"Let's play",title:'Classic Sudoku',subtitle:'Take a short break without leaving the panel',difficulty:'Difficulty',easy:'Easy',medium:'Medium',hard:'Hard',expert:'Expert',newGame:'New game',time:'Time',mistakes:'Mistakes',hints:'Hints',notes:'Notes',erase:'Erase',hint:'Hint',check:'Check',pause:'Pause',resume:'Resume',settings:'Settings',highlight:'Highlight related cells',showMistakes:'Show mistakes',showTimer:'Show timer',autoNotes:'Remove used notes',paused:'Game paused',ready:'Select a cell and enter a number.',correct:'Everything is correct so far.',incomplete:'There are empty cells.',hasErrors:'Errors found: ',complete:'Done! Sudoku solved.',failed:'Mistake limit reached. Start a new game.',noHints:'No hints remain for this game.',confirmNew:'Start a new game? The current game will be replaced.',close:'Close game',cell:'Cell'}};
const STORE='sudoku-ui-game-v1',PREFS='sudoku-ui-game-prefs-v1',targets={easy:42,medium:34,hard:28,expert:24},limits={easy:5,medium:4,hard:3,expert:2};
const $=s=>document.querySelector(s),tr=k=>(TEXT[document.documentElement.lang==='en'?'en':'ru'][k]||k);
let game=null,prefs=loadPrefs(),selected=-1,notesMode=false,opened=false,timer=null,message='',messageKind='';
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function solvedGrid(){const bands=shuffle([0,1,2]),stacks=shuffle([0,1,2]),rows=bands.flatMap(b=>shuffle([0,1,2]).map(r=>b*3+r)),cols=stacks.flatMap(b=>shuffle([0,1,2]).map(c=>b*3+c)),nums=shuffle([1,2,3,4,5,6,7,8,9]);return rows.flatMap(r=>cols.map(c=>nums[(r*3+Math.floor(r/3)+c)%9]))}
function candidates(board,idx){const used=new Set, r=Math.floor(idx/9),c=idx%9;for(let i=0;i<9;i++){used.add(board[r*9+i]);used.add(board[i*9+c])}const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let y=0;y<3;y++)for(let x=0;x<3;x++)used.add(board[(br+y)*9+bc+x]);return [1,2,3,4,5,6,7,8,9].filter(n=>!used.has(n))}
function countSolutions(board,limit=2){let best=-1,opts=null;for(let i=0;i<81;i++)if(!board[i]){const c=candidates(board,i);if(!c.length)return 0;if(!opts||c.length<opts.length){best=i;opts=c;if(c.length===1)break}}if(best<0)return 1;let count=0;for(const n of opts){board[best]=n;count+=countSolutions(board,limit-count);board[best]=0;if(count>=limit)break}return count}
function makeGame(level){const solution=solvedGrid(),puzzle=solution.slice(),order=shuffle([...Array(81).keys()]),target=targets[level]||targets.medium;let clues=81;for(const idx of order){if(clues<=target)break;const old=puzzle[idx];puzzle[idx]=0;if(countSolutions(puzzle.slice())===1)clues--;else puzzle[idx]=old}return{version:1,level,puzzle,solution,entries:puzzle.slice(),notes:Array(81).fill(0),elapsed:0,mistakes:0,hintsUsed:0,paused:false,completed:false,failed:false}}
function validGame(x){return x&&x.version===1&&targets[x.level]&&Array.isArray(x.puzzle)&&x.puzzle.length===81&&Array.isArray(x.solution)&&x.solution.length===81&&Array.isArray(x.entries)&&x.entries.length===81&&Array.isArray(x.notes)&&x.notes.length===81}
function loadGame(){try{const x=JSON.parse(localStorage.getItem(STORE));if(!validGame(x))return null;x.hintsUsed=Number.isFinite(x.hintsUsed)?x.hintsUsed:0;x.failed=!!x.failed||(!x.completed&&x.mistakes>=limits[x.level]);return x}catch{return null}}
function loadPrefs(){try{return{highlight:true,showMistakes:true,showTimer:true,autoNotes:true,...JSON.parse(localStorage.getItem(PREFS)||'{}')}}catch{return{highlight:true,showMistakes:true,showTimer:true,autoNotes:true}}}
function save(){if(game)localStorage.setItem(STORE,JSON.stringify(game));localStorage.setItem(PREFS,JSON.stringify(prefs))}
function ensureDialog(){if($('#gameBackdrop'))return;const root=document.createElement('div');root.id='gameBackdrop';root.className='game-backdrop hidden';root.innerHTML=`<section class="game-dialog" role="dialog" aria-modal="true" aria-labelledby="gameTitle"><button class="game-close" type="button" data-game="close">×</button><div class="game-heading"><div><h2 id="gameTitle"></h2><p data-game-text="subtitle"></p></div><div class="game-stats"><span><i data-game-text="time"></i><b id="gameTime">00:00</b></span><span><i data-game-text="mistakes"></i><b id="gameMistakes">0 / 5</b></span><span><i data-game-text="hints"></i><b id="gameHints">0 / 5</b></span></div></div><div class="game-layout"><div class="game-board-wrap"><div id="gameBoard" class="game-board"></div><div id="gamePaused" class="game-paused hidden"></div></div><aside class="game-side"><div class="game-select-row"><select id="gameDifficulty" class="game-select"><option value="easy"></option><option value="medium"></option><option value="hard"></option><option value="expert"></option></select><button class="game-new" type="button" data-game="new"></button></div><div id="gameNumbers" class="game-numbers"></div><div class="game-tools"><button type="button" data-game="notes"></button><button type="button" data-game="erase"></button><button type="button" data-game="hint"></button><button type="button" data-game="check"></button><button type="button" data-game="pause"></button><button type="button" data-game="settings"></button></div><div id="gameSettings" class="game-settings hidden"><label><span data-game-text="highlight"></span><input type="checkbox" data-pref="highlight"></label><label><span data-game-text="showMistakes"></span><input type="checkbox" data-pref="showMistakes"></label><label><span data-game-text="showTimer"></span><input type="checkbox" data-pref="showTimer"></label><label><span data-game-text="autoNotes"></span><input type="checkbox" data-pref="autoNotes"></label></div><div id="gameMessage" class="game-message"></div></aside></div></section>`;document.body.append(root);root.addEventListener('click',onClick);root.addEventListener('change',onChange);root.addEventListener('click',e=>{if(e.target===root)closeGame()});}
function updateLanguage(){const open=$('#gameOpen');if(open){open.textContent=tr('play');open.title=tr('play')}const root=$('#gameBackdrop');if(!root)return;$('#gameTitle').textContent=tr('title');root.querySelectorAll('[data-game-text]').forEach(x=>x.textContent=tr(x.dataset.gameText));root.querySelector('[data-game="new"]').textContent=tr('newGame');for(const o of $('#gameDifficulty').options)o.textContent=tr(o.value);for(const key of ['notes','erase','hint','check','pause','settings']){const b=root.querySelector(`[data-game="${key}"]`);if(b)b.textContent=key==='pause'&&game?.paused?tr('resume'):tr(key)}root.querySelector('[data-game="close"]').setAttribute('aria-label',tr('close'));if(!message)message=game?.completed?tr('complete'):tr('ready');render()}
function openGame(){ensureDialog();game=loadGame()||makeGame('medium');selected=game.entries.findIndex((n,i)=>!game.puzzle[i]&&!n);if(selected<0)selected=game.puzzle.findIndex(n=>!n);opened=true;message=game.completed?tr('complete'):game.failed?tr('failed'):tr('ready');messageKind=game.completed?'success':game.failed?'error':'';$('#gameBackdrop').classList.remove('hidden');document.body.style.overflow='hidden';updateLanguage();startTimer()}
function closeGame(){opened=false;save();$('#gameBackdrop')?.classList.add('hidden');document.body.style.overflow='';}
function startTimer(){if(timer)return;timer=setInterval(()=>{if(opened&&game&&!game.paused&&!game.completed&&!game.failed){game.elapsed++;if(game.elapsed%10===0)save();renderStats()}},1000)}
function formatTime(s){const h=Math.floor(s/3600),m=Math.floor(s%3600/60),n=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(n).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(n).padStart(2,'0')}`}
function renderStats(){if(!game||!$('#gameTime'))return;const limit=limits[game.level];$('#gameTime').textContent=prefs.showTimer?formatTime(game.elapsed):'—';$('#gameMistakes').textContent=prefs.showMistakes?`${game.mistakes} / ${limit}`:'—';$('#gameHints').textContent=`${game.hintsUsed} / ${limit}`}
function peers(a,b){const ar=Math.floor(a/9),ac=a%9,br=Math.floor(b/9),bc=b%9;return ar===br||ac===bc||(Math.floor(ar/3)===Math.floor(br/3)&&Math.floor(ac/3)===Math.floor(bc/3))}
function render(){if(!game||!$('#gameBoard'))return;const board=$('#gameBoard'),chosen=game.entries[selected],blocked=game.paused||game.completed||game.failed,limit=limits[game.level],hintsLeft=Math.max(0,limit-game.hintsUsed);board.innerHTML=game.entries.map((n,i)=>{const given=!!game.puzzle[i],related=prefs.highlight&&selected>=0&&i!==selected&&peers(i,selected),same=prefs.highlight&&chosen&&n===chosen&&i!==selected,wrong=prefs.showMistakes&&n&&!given&&n!==game.solution[i],mask=game.notes[i]||0,notes=!n?[1,2,3,4,5,6,7,8,9].map(v=>`<span>${mask&(1<<v)?v:''}</span>`).join(''):'';return `<button type="button" class="game-cell${given?' given':''}${related?' related':''}${same?' same':''}${i===selected?' selected':''}${wrong?' wrong':''}" data-cell="${i}" aria-label="${tr('cell')} ${Math.floor(i/9)+1}, ${i%9+1}">${n||''}${notes?`<i class="game-notes">${notes}</i>`:''}</button>`}).join('');$('#gameDifficulty').value=game.level;$('#gamePaused').textContent=game.failed?tr('failed'):tr('paused');$('#gamePaused').classList.toggle('hidden',!game.paused&&!game.failed);const pause=$('[data-game="pause"]');if(pause){pause.textContent=game.paused?tr('resume'):tr('pause');pause.disabled=game.completed||game.failed}const notes=$('[data-game="notes"]');if(notes){notes.classList.toggle('active',notesMode);notes.disabled=blocked}for(const key of ['erase','check']){const b=$(`[data-game="${key}"]`);if(b)b.disabled=blocked}const hintButton=$('[data-game="hint"]');if(hintButton){hintButton.textContent=`${tr('hint')} · ${hintsLeft}`;hintButton.disabled=blocked||hintsLeft===0}for(const button of document.querySelectorAll('[data-number]')){const n=+button.dataset.number,done=game.entries.reduce((count,v,i)=>count+(v===n&&v===game.solution[i]?1:0),0)===9;button.disabled=blocked||done}for(const input of document.querySelectorAll('#gameSettings [data-pref]'))input.checked=!!prefs[input.dataset.pref];const box=$('#gameMessage');box.textContent=message||tr('ready');box.className='game-message'+(messageKind?' '+messageKind:'');renderStats()}
function removePeerNotes(idx,n){for(let i=0;i<81;i++)if(peers(i,idx))game.notes[i]&=~(1<<n)}
function enter(n){if(!game||game.paused||game.completed||game.failed||selected<0||game.puzzle[selected])return;if(notesMode){game.notes[selected]^=1<<n}else{const was=game.entries[selected];game.entries[selected]=n;game.notes[selected]=0;if(n!==game.solution[selected]&&was!==n)game.mistakes++;if(n===game.solution[selected]&&prefs.autoNotes)removePeerNotes(selected,n)}message='';messageKind='';if(game.mistakes>=limits[game.level]){game.failed=true;message=tr('failed');messageKind='error'}else finishIfComplete();save();render()}
function erase(){if(!game||game.paused||game.completed||game.failed||selected<0||game.puzzle[selected])return;game.entries[selected]=0;game.notes[selected]=0;message='';messageKind='';save();render()}
function hint(){if(!game||game.paused||game.completed||game.failed)return;const limit=limits[game.level];if(game.hintsUsed>=limit){message=tr('noHints');messageKind='';render();return}let i=selected;if(i<0||game.puzzle[i]||game.entries[i]===game.solution[i])i=game.entries.findIndex((n,j)=>!game.puzzle[j]&&n!==game.solution[j]);if(i<0)return;selected=i;game.entries[i]=game.solution[i];game.notes[i]=0;game.hintsUsed++;if(prefs.autoNotes)removePeerNotes(i,game.solution[i]);message='';messageKind='';finishIfComplete();save();render()}
function check(){if(!game||game.paused||game.failed)return;const errors=game.entries.reduce((a,n,i)=>a+(n&&n!==game.solution[i]?1:0),0),empty=game.entries.some(n=>!n);if(errors){message=tr('hasErrors')+errors;messageKind=''}else if(empty){message=tr('incomplete');messageKind=''}else{finishIfComplete()}render()}
function finishIfComplete(){if(game.entries.every((n,i)=>n===game.solution[i])){game.completed=true;game.paused=false;message=tr('complete');messageKind='success'} }
function newGame(force=false){if(!force&&game&&!game.completed&&game.entries.some((n,i)=>!game.puzzle[i]&&n)&&!confirm(tr('confirmNew'))){render();return}const level=$('#gameDifficulty')?.value||game?.level||'medium';game=makeGame(level);selected=game.entries.findIndex(n=>!n);notesMode=false;message=tr('ready');messageKind='';save();render()}
function togglePause(){if(!game||game.completed||game.failed)return;game.paused=!game.paused;message=game.paused?tr('paused'):tr('ready');messageKind='';save();render()}
function onClick(e){const cell=e.target.closest('[data-cell]');if(cell){if(!game.paused){selected=+cell.dataset.cell;render()}return}const b=e.target.closest('[data-game]');if(!b)return;const action=b.dataset.game;if(action==='close')closeGame();else if(action==='new')newGame();else if(action==='notes'){notesMode=!notesMode;render()}else if(action==='erase')erase();else if(action==='hint')hint();else if(action==='check')check();else if(action==='pause')togglePause();else if(action==='settings')$('#gameSettings').classList.toggle('hidden')}
function onChange(e){if(e.target.id==='gameDifficulty')newGame();if(e.target.dataset.pref){prefs[e.target.dataset.pref]=e.target.checked;save();render()}}
function moveSelection(delta){if(selected<0)selected=0;else selected=Math.max(0,Math.min(80,selected+delta));render()}
document.addEventListener('keydown',e=>{if(!opened||e.target.matches('select,input'))return;if(/^[1-9]$/.test(e.key)){e.preventDefault();enter(+e.key)}else if(e.key==='Backspace'||e.key==='Delete'||e.key==='0'){e.preventDefault();erase()}else if(e.key.toLowerCase()==='n'){notesMode=!notesMode;render()}else if(e.key==='ArrowLeft'){e.preventDefault();moveSelection(-1)}else if(e.key==='ArrowRight'){e.preventDefault();moveSelection(1)}else if(e.key==='ArrowUp'){e.preventDefault();moveSelection(-9)}else if(e.key==='ArrowDown'){e.preventDefault();moveSelection(9)}else if(e.key==='Escape')closeGame()});
function init(){const button=$('#gameOpen');if(!button)return;button.addEventListener('click',openGame);ensureDialog();$('#gameNumbers').innerHTML=[1,2,3,4,5,6,7,8,9].map(n=>`<button type="button" class="game-number" data-number="${n}">${n}</button>`).join('');$('#gameNumbers').addEventListener('click',e=>{const b=e.target.closest('[data-number]');if(b)enter(+b.dataset.number)});updateLanguage();new MutationObserver(updateLanguage).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
init();
})();
