const HELP={ru:{
name:'<b>Название</b><p>Имя подключения для твоего удобства. Никак не влияет на работу протокола, видно только в этой панели.</p>',
port:'<b>Порт</b><p>Порт, на котором сервер слушает входящие Sudoku-соединения. Меняй, если порт уже занят другим сервисом или хочешь скрыть сервис от портового сканирования.</p>',
aead:'<b>Шифрование</b><p>Алгоритм AEAD-шифрования полезной нагрузки внутри судоку-паззлов. <b>ChaCha20-Poly1305</b> — стандартный выбор, быстрый на мобильных CPU без AES-ускорения.</p>',
table:'<b>Тип таблицы</b><p>Определяет, как байты кодируются в судоку-решения и как выглядит трафик «снаружи» в каждом направлении. <code>up_ascii_down_entropy</code> смещает исходящий трафик к печатным ASCII-символам, а входящий — к высокоэнтропийному шуму. Влияет на то, под что маскируется поток.</p>',
padding:'<b>Padding min / Padding max</b><p>Диапазон случайного довеска (в байтах) к каждой записи данных, чтобы скрыть реальный размер передаваемых пакетов. Слишком узкий диапазон — трафик легче отличить по размеру пакетов; слишком широкий — лишний оверхед и потеря скорости.</p>',
pure:'<b>Pure Downlink</b><p><b>Выключено (по умолчанию):</b> входящий трафик оптимизирован по скорости. <b>Включено:</b> весь нисходящий поток тоже кодируется через чистое судоку-представление — медленнее, но максимально единообразный «отпечаток» трафика в обе стороны.</p>',
http:'<b>HTTP Mask</b><p>Заворачивает соединение в HTTP(S)-обёртку — трафик выглядит как обычный запрос к веб-серверу. Полезно, если провайдер режет по «нетипичным» TCP-соединениям или нужно завести протокол через CDN/reverse proxy.</p>',
multiplex:'<b>Multiplex</b><p><code>off</code> — каждое соединение отдельным туннелем. <code>auto</code> — переиспользует только уже установленное HTTP Mask-соединение. <code>on</code> — несколько сессий/адресов мультиплексируются в одном сыром TCP или HTTP Mask-соединении. Экономит хендшейки при множестве параллельных запросов.</p>',
httpMode:'<b>HTTP mode</b><p>Активно только если HTTP Mask включён. <code>legacy</code> — старое поведение. <code>stream</code>/<code>poll</code>/<code>auto</code>/<code>ws</code> — режимы, совместимые с проксированием через CDN или reverse proxy (например Cloudflare). Выбирай их, если сервер стоит за прокси-фронтом, а не принимает трафик напрямую.</p>'
},en:{
name:'<b>Name</b><p>A convenient label visible only in this panel. It does not affect the protocol.</p>',port:'<b>Port</b><p>The port on which the server accepts incoming Sudoku connections. Change it if another service already uses it or to reduce obvious port scanning.</p>',aead:'<b>Encryption</b><p>The AEAD algorithm protecting payloads inside Sudoku puzzles. ChaCha20-Poly1305 is the standard choice and performs well on mobile CPUs without AES acceleration.</p>',table:'<b>Table type</b><p>Controls how bytes are encoded as Sudoku solutions and how each traffic direction appears externally. <code>up_ascii_down_entropy</code> makes uplink resemble printable ASCII and downlink resemble high-entropy noise.</p>',padding:'<b>Padding min / Padding max</b><p>The random number of bytes added to each data record to conceal real packet sizes. A narrow range is easier to fingerprint; a wide range adds overhead.</p>',pure:'<b>Pure Downlink</b><p><b>Off (default):</b> downlink is optimized for speed. <b>On:</b> all downlink traffic uses the pure Sudoku representation, which is slower but gives both directions a more uniform fingerprint.</p>',http:'<b>HTTP Mask</b><p>Wraps the connection in HTTP(S) so it resembles ordinary web traffic. Useful for restrictive networks or operation through a CDN/reverse proxy.</p>',multiplex:'<b>Multiplex</b><p><code>off</code> uses a separate tunnel per connection. <code>auto</code> reuses an existing HTTP Mask connection. <code>on</code> multiplexes several sessions through one raw TCP or HTTP Mask connection.</p>',httpMode:'<b>HTTP mode</b><p>Active only with HTTP Mask. <code>legacy</code> is the old behavior. <code>stream</code>, <code>poll</code>, <code>auto</code>, and <code>ws</code> are intended for CDN or reverse-proxy compatibility.</p>'
}};
